import 'package:path_provider/path_provider.dart';
import '../../features/finance/data/models/bank_account.dart';
import '../../features/finance/data/models/transaction.dart';
import '../../features/settings/data/models/app_settings.dart';
import '../../objectbox.g.dart'; // Automatically generated by build_runner

class ObjectBoxStore {
  late final Store store;
  late final Box<BankAccount> accountBox;
  late final Box<Transaction> transactionBox;
  late final Box<AppSettings> appSettingsBox;

  ObjectBoxStore(this.store) {
    accountBox = Box<BankAccount>(store);
    transactionBox = Box<Transaction>(store);
    appSettingsBox = Box<AppSettings>(store);
  }

  /// Open the database and return the ObjectBoxStore helper instance
  static Future<ObjectBoxStore> create() async {
    final docsDir = await getApplicationDocumentsDirectory();
    final storeDir = '${docsDir.path}/ob-expense-manager';

    // openStore is a generated method from objectbox.g.dart
    final store = await openStore(directory: storeDir);
    return ObjectBoxStore(store);
  }
}
