// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/finance/data/models/bank_account.dart';
import 'features/finance/data/models/transaction.dart';
import 'features/settings/data/models/app_settings.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 8802506316537374420),
      name: 'AppSettings',
      lastPropertyId: const obx_int.IdUid(10, 6690811873824307119),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7256860890310187053),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4976230990919734639),
            name: 'localeCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7144109322137174053),
            name: 'isDarkMode',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7512993213912617211),
            name: 'selectedCurrency',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4988722608824650025),
            name: 'isTimeBasedTheme',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5443055468223975253),
            name: 'autoDarkStartHour',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1376268535155918939),
            name: 'autoDarkStartMinute',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5459023477269703508),
            name: 'autoLightStartHour',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 9087015243671446526),
            name: 'autoLightStartMinute',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6690811873824307119),
            name: 'isSystemTheme',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2287882438224208140),
      name: 'BankAccount',
      lastPropertyId: const obx_int.IdUid(7, 8805318785506266679),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3901618846588862910),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3961269652650836905),
            name: 'accountId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 6962134872290937056)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3090763550666025019),
            name: 'accountName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5787334773336967155),
            name: 'accountType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4928902738919692629),
            name: 'currency',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8264850860666819072),
            name: 'startingBalance',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8805318785506266679),
            name: 'currentBalance',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 448627644247980718),
      name: 'Transaction',
      lastPropertyId: const obx_int.IdUid(9, 4832984016873531975),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2970500730520187308),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4374018232518968931),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3429459534269681800),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5880085488712724670),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1242110687955386138),
            name: 'transactionType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2465993030697591274),
            name: 'notes',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2446875213477712496),
            name: 'dbTags',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4135883081612977497),
            name: 'accountRefId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 7491988211804394663),
            relationTarget: 'BankAccount'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4832984016873531975),
            name: 'tagsList',
            type: 30,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 448627644247980718),
      lastIndexId: const obx_int.IdUid(2, 7491988211804394663),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSettings: obx_int.EntityDefinition<AppSettings>(
        model: _entities[0],
        toOneRelations: (AppSettings object) => [],
        toManyRelations: (AppSettings object) => {},
        getId: (AppSettings object) => object.id,
        setId: (AppSettings object, int id) {
          object.id = id;
        },
        objectToFB: (AppSettings object, fb.Builder fbb) {
          final localeCodeOffset = fbb.writeString(object.localeCode);
          final selectedCurrencyOffset =
              fbb.writeString(object.selectedCurrency);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, localeCodeOffset);
          fbb.addBool(2, object.isDarkMode);
          fbb.addOffset(3, selectedCurrencyOffset);
          fbb.addBool(4, object.isTimeBasedTheme);
          fbb.addInt64(5, object.autoDarkStartHour);
          fbb.addInt64(6, object.autoDarkStartMinute);
          fbb.addInt64(7, object.autoLightStartHour);
          fbb.addInt64(8, object.autoLightStartMinute);
          fbb.addBool(9, object.isSystemTheme);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final localeCodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final isDarkModeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final selectedCurrencyParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final isTimeBasedThemeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final isSystemThemeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false);
          final autoDarkStartHourParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final autoDarkStartMinuteParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final autoLightStartHourParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final autoLightStartMinuteParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final object = AppSettings(
              id: idParam,
              localeCode: localeCodeParam,
              isDarkMode: isDarkModeParam,
              selectedCurrency: selectedCurrencyParam,
              isTimeBasedTheme: isTimeBasedThemeParam,
              isSystemTheme: isSystemThemeParam,
              autoDarkStartHour: autoDarkStartHourParam,
              autoDarkStartMinute: autoDarkStartMinuteParam,
              autoLightStartHour: autoLightStartHourParam,
              autoLightStartMinute: autoLightStartMinuteParam);

          return object;
        }),
    BankAccount: obx_int.EntityDefinition<BankAccount>(
        model: _entities[1],
        toOneRelations: (BankAccount object) => [],
        toManyRelations: (BankAccount object) => {},
        getId: (BankAccount object) => object.id,
        setId: (BankAccount object, int id) {
          object.id = id;
        },
        objectToFB: (BankAccount object, fb.Builder fbb) {
          final accountIdOffset = fbb.writeString(object.accountId);
          final accountNameOffset = fbb.writeString(object.accountName);
          final accountTypeOffset = fbb.writeString(object.accountType);
          final currencyOffset = fbb.writeString(object.currency);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, accountIdOffset);
          fbb.addOffset(2, accountNameOffset);
          fbb.addOffset(3, accountTypeOffset);
          fbb.addOffset(4, currencyOffset);
          fbb.addFloat64(5, object.startingBalance);
          fbb.addFloat64(6, object.currentBalance);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final accountIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final accountNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final accountTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final currencyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final startingBalanceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final currentBalanceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = BankAccount(
              id: idParam,
              accountId: accountIdParam,
              accountName: accountNameParam,
              accountType: accountTypeParam,
              currency: currencyParam,
              startingBalance: startingBalanceParam,
              currentBalance: currentBalanceParam);

          return object;
        }),
    Transaction: obx_int.EntityDefinition<Transaction>(
        model: _entities[2],
        toOneRelations: (Transaction object) => [object.accountRef],
        toManyRelations: (Transaction object) => {},
        getId: (Transaction object) => object.id,
        setId: (Transaction object, int id) {
          object.id = id;
        },
        objectToFB: (Transaction object, fb.Builder fbb) {
          final categoryOffset = fbb.writeString(object.category);
          final transactionTypeOffset = fbb.writeString(object.transactionType);
          final notesOffset = fbb.writeString(object.notes);
          final dbTagsOffset = fbb.writeString(object.dbTags);
          final tagsListOffset = fbb.writeList(
              object.tagsList.map(fbb.writeString).toList(growable: false));
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.amount);
          fbb.addInt64(2, object.date.millisecondsSinceEpoch);
          fbb.addOffset(3, categoryOffset);
          fbb.addOffset(4, transactionTypeOffset);
          fbb.addOffset(5, notesOffset);
          fbb.addOffset(6, dbTagsOffset);
          fbb.addInt64(7, object.accountRef.targetId);
          fbb.addOffset(8, tagsListOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final transactionTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final notesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = Transaction(
              id: idParam,
              amount: amountParam,
              date: dateParam,
              category: categoryParam,
              transactionType: transactionTypeParam,
              notes: notesParam)
            ..dbTags = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..tagsList = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 20, []);
          object.accountRef.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.accountRef.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// see [AppSettings.id]
  static final id =
      obx.QueryIntegerProperty<AppSettings>(_entities[0].properties[0]);

  /// see [AppSettings.localeCode]
  static final localeCode =
      obx.QueryStringProperty<AppSettings>(_entities[0].properties[1]);

  /// see [AppSettings.isDarkMode]
  static final isDarkMode =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[2]);

  /// see [AppSettings.selectedCurrency]
  static final selectedCurrency =
      obx.QueryStringProperty<AppSettings>(_entities[0].properties[3]);

  /// see [AppSettings.isTimeBasedTheme]
  static final isTimeBasedTheme =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[4]);

  /// see [AppSettings.autoDarkStartHour]
  static final autoDarkStartHour =
      obx.QueryIntegerProperty<AppSettings>(_entities[0].properties[5]);

  /// see [AppSettings.autoDarkStartMinute]
  static final autoDarkStartMinute =
      obx.QueryIntegerProperty<AppSettings>(_entities[0].properties[6]);

  /// see [AppSettings.autoLightStartHour]
  static final autoLightStartHour =
      obx.QueryIntegerProperty<AppSettings>(_entities[0].properties[7]);

  /// see [AppSettings.autoLightStartMinute]
  static final autoLightStartMinute =
      obx.QueryIntegerProperty<AppSettings>(_entities[0].properties[8]);

  /// see [AppSettings.isSystemTheme]
  static final isSystemTheme =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[9]);
}

/// [BankAccount] entity fields to define ObjectBox queries.
class BankAccount_ {
  /// see [BankAccount.id]
  static final id =
      obx.QueryIntegerProperty<BankAccount>(_entities[1].properties[0]);

  /// see [BankAccount.accountId]
  static final accountId =
      obx.QueryStringProperty<BankAccount>(_entities[1].properties[1]);

  /// see [BankAccount.accountName]
  static final accountName =
      obx.QueryStringProperty<BankAccount>(_entities[1].properties[2]);

  /// see [BankAccount.accountType]
  static final accountType =
      obx.QueryStringProperty<BankAccount>(_entities[1].properties[3]);

  /// see [BankAccount.currency]
  static final currency =
      obx.QueryStringProperty<BankAccount>(_entities[1].properties[4]);

  /// see [BankAccount.startingBalance]
  static final startingBalance =
      obx.QueryDoubleProperty<BankAccount>(_entities[1].properties[5]);

  /// see [BankAccount.currentBalance]
  static final currentBalance =
      obx.QueryDoubleProperty<BankAccount>(_entities[1].properties[6]);
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// see [Transaction.id]
  static final id =
      obx.QueryIntegerProperty<Transaction>(_entities[2].properties[0]);

  /// see [Transaction.amount]
  static final amount =
      obx.QueryDoubleProperty<Transaction>(_entities[2].properties[1]);

  /// see [Transaction.date]
  static final date =
      obx.QueryDateProperty<Transaction>(_entities[2].properties[2]);

  /// see [Transaction.category]
  static final category =
      obx.QueryStringProperty<Transaction>(_entities[2].properties[3]);

  /// see [Transaction.transactionType]
  static final transactionType =
      obx.QueryStringProperty<Transaction>(_entities[2].properties[4]);

  /// see [Transaction.notes]
  static final notes =
      obx.QueryStringProperty<Transaction>(_entities[2].properties[5]);

  /// see [Transaction.dbTags]
  static final dbTags =
      obx.QueryStringProperty<Transaction>(_entities[2].properties[6]);

  /// see [Transaction.accountRef]
  static final accountRef = obx.QueryRelationToOne<Transaction, BankAccount>(
      _entities[2].properties[7]);

  /// see [Transaction.tagsList]
  static final tagsList =
      obx.QueryStringVectorProperty<Transaction>(_entities[2].properties[8]);
}
